name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - action-test
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List root directory
        run: ls -al /

      - name: List home directory
        run: ls -al /home/runner

      - name: List work directory
        run: ls -al /home/runner/work

      - name: List repository directory
        run: ls -al /home/runner/work/RapidTube/RapidTube

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: /home/runner/work/RapidTube/RapidTube

      - name: Build the project
        run: npm run build
        working-directory: /home/runner/work/RapidTube/RapidTube

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAPIDTUBEPRO }}
          channelId: live
          projectId: rapidtubepro
